version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - docker -v
      - docker-compose -v
      - groups
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker pull 391634500132.dkr.ecr.eu-central-1.amazonaws.com/laravel_8:latest
      - printenv | sed 's/=\(.*\)/="\1"/' > .env
      # Copy latest team-version branch source code to master container
      - aws s3 cp s3://s3-cheqsite-test-bucket/team-version/source-code.zip .
      - docker-compose up -d
  build:
    commands:
      - docker ps -a
      - docker container ls
      - docker exec docker-compose_web_1 pwd
      - docker exec docker-compose_web_1 ls -la /var/www/html
      - docker exec docker-compose_web_1 cat .env
      - docker exec docker-compose_web_1 unzip source-code.zip
      - docker exec docker-compose_web_1 composer install
      - docker exec docker-compose_web_1 npm install
      - docker exec docker-compose_web_1 php artisan key:generate
      - docker exec docker-compose_web_1 php artisan migrate:fresh
      - echo "test build"

