version: 0.2

phases:
  pre_build:
    commands:
      - docker -v
      - docker-compose -v
      - service docker status
      - groups
      - docker-compose --verbose up -d
  build:
    commands:
      - echo "test build"

