version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - docker -v
      - docker-compose -v
      - groups
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - printenv | sed 's/=\(.*\)/="\1"/' > .env
      - docker-compose up -d
  build:
    commands:
      - echo "test build"

