version: "3.3"  # optional since v1.27.0
services:
  web:
    image: 391634500132.dkr.ecr.eu-central-1.amazonaws.com/laravel_8:latest
    ports:
      - "443:443"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
volumes:
  db_data: {}
