version: "3.3"  # optional since v1.27.0
services:
  web:
    image: 391634500132.dkr.ecr.eu-central-1.amazonaws.com/laravel_8:latest
    ports:
      - "443:443"
    networks:
      docker-compose_default:
        ipv4_address: 172.18.0.4
    restart: always
    volumes:
      - ${PWD}/.env:/var/www/html/.env
      - ${PWD}/source-code.zip:/var/www/html/source-code.zip
      - /root/node_modules:/var/www/html/node_modules
      - /root/vendor:/var/www/html/vendor
    links:
      - mysql
      - couchbase
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      docker-compose_default:
        ipv4_address: 172.18.0.2
  couchbase:
    image: couchbase:6.6.2
    restart: always
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    networks:
      docker-compose_default:
        ipv4_address: 172.18.0.3
    volumes:
      - ${PWD}/couchbase-cluster-init.sh:/usr/local/bin/couchbase-cluster-init.sh
volumes:
  db_data: {}
